[package]
name = "lighthouse_validator_store"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[features]
default = ["beacon-node-fallback"]
beacon-node-fallback = ["doppelganger_service/beacon-node-fallback"]
pq-devnet = [
    "consensus_signature/pq-wire",
    "doppelganger_service/pq-devnet",
    "eth2/pq-devnet",
    "initialized_validators/pq-devnet",
    "signing_method/pq-devnet",
    "slashing_protection/pq-devnet",
    "types/pq-devnet",
    "validator_store/pq-devnet",
]

[dependencies]
account_utils = { workspace = true }
bls = { workspace = true }
consensus_signature = { workspace = true }
doppelganger_service = { path = "../doppelganger_service", default-features = false }
either = { workspace = true }
environment = { workspace = true }
eth2 = { workspace = true }
futures = { workspace = true }
initialized_validators = { workspace = true }
logging = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
signing_method = { workspace = true }
slashing_protection = { workspace = true }
slot_clock = { workspace = true }
task_executor = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }
validator_metrics = { workspace = true }
validator_store = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
logging = { workspace = true }
