[package]
name = "zkvm_execution_layer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1" #TODO(zkproofs): Remove
lru = "0.12"
hashbrown = "0.15"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
thiserror = "2"
types = { path = "../consensus/types" }
execution_layer = { path = "../beacon_node/execution_layer" }
pico-vm = { git = "https://github.com/brevis-network/pico.git", branch = "ethproofs-pico-v1.3.0" }
proofman-verifier = { git = "https://github.com/0xPolygonHermez/pil2-proofman.git", tag = "v0.16.0" }
sp1-verifier = { git = "https://github.com/succinctlabs/hypercube-verifier.git", branch = "ethproofs_demo" }
openvm-verify-stark-host = { git = "https://github.com/openvm-org/openvm.git", branch = "develop-v2.0.0-rc.1", default-features = false }
bitcode = { version = "0.6.5", default-features = false, features = ["serde"] }
serde = { version = "1.0.201", default-features = false, features = ["derive"] }
bincode = { workspace = true }
tempfile = { workspace = true }
reqwest = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
once_cell = { workspace = true }
tracing = { workspace = true }
base64 = "0.22"
# Airbender verifier dependencies
full_statement_verifier = { git = "https://github.com/matter-labs/zksync-airbender", rev = "cef19b3", default-features = false, features = ["unified_verifier_only_security_80"] }
verifier_common = { git = "https://github.com/matter-labs/zksync-airbender", rev = "cef19b3", default-features = false, features = ["proof_utils"] }
airbender-prover = { package = "prover", git = "https://github.com/matter-labs/zksync-airbender", rev = "cef19b3", default-features = false, features = ["definitions_only"] }
bincode2 = { package = "bincode", version = "2", features = ["serde"] }
flate2 = "1"

[dev-dependencies]
mockall = "0.12"
