[package]
name = "signing_method"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[features]
default = []
pq-devnet = [
    "consensus_signature/pq-devnet",
    "pq_signing/pq-devnet",
    "types/pq-devnet",
]

[dependencies]
bls = { workspace = true }
consensus_signature = { workspace = true }
eth2_keystore = { workspace = true }
ethereum_serde_utils = { workspace = true }
lockfile = { workspace = true }
parking_lot = { workspace = true }
pq_signing = { workspace = true, optional = true }
reqwest = { workspace = true }
serde = { workspace = true }
task_executor = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }
url = { workspace = true }
validator_metrics = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
